#!/bin/bash

mkdir pvuln
# Run gf xss with input from endpoints_f.txt and append output to xss.txt
gf xss < endpoints_f.txt >> pvuln/xss.txt

# Run gf ssrf with input from endpoints_f.txt and append output to ssrf.txt
gf ssrf < endpoints_f.txt >> pvuln/ssrf.txt

# Run gf redirect with input from endpoints_f.txt and append output to redirect.txt
gf redirect < endpoints_f.txt >> pvuln/redirect.txt

# Run gf rce with input from endpoints_f.txt and append output to rce.txt
gf rce < endpoints_f.txt >> pvuln/rce.txt

# Run gf idor with input from endpoints_f.txt and append output to idor.txt
gf idor < endpoints_f.txt >> pvuln/idor.txt

# Run gf sqli with input from endpoints_f.txt and append output to sqli.txt
gf sqli < endpoints_f.txt >> pvuln/sqli.txt

# Run gf lfi with input from endpoints_f.txt and append output to lfi.txt
gf lfi < endpoints_f.txt >> pvuln/lfi.txt

# Run gf ssti with input from endpoints_f.txt and append output to ssti.txt
gf ssti < endpoints_f.txt >> pvuln/ssti.txt

# Run gf debug_logic with input from endpoints_f.txt and append output to debug_logic.txt
gf debug_logic < endpoints_f.txt >> pvuln/debug_logic.txt
